%YAML 1.1
---
version: "3.9"

services:
  owl-tkn:
    image: tinyluma/owl-tkn
    container_name: owl_tkn
    read_only: true
    build:
      context: .
    environment:
      - OWL_ACCOUNTS=${OWL_ACCOUNTS}
    volumes:
      - "./data:/data:rw"
    logging:
      driver: json-file
      options:
        max-size: 10m
    restart: unless-stopped